spring:
  datasource:
    url: jdbc:h2:mem:taskdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update  # safe for production
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: INFO

task:
  limits:
    maxTasksPerUser: 20
    autoDeleteOverdue: true
